spring:
  application:
    name: spring-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      default-filters:
        - name: RequestSize
          args:
            maxSize: 50000000
      routes:
        - id: spring-app
          uri: lb://spring-app
          predicates:
            - Path=/app/**

server:
  port: 443

---
spring:
  profiles: dev
eureka:
  #  instance:
  #    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    peer-node-read-timeout-ms: 2000