spring:
  application:
    name: spring-euraka
  profiles:
    active: dev

server:
  port: 8761

# Exposing 17 endpoint(s) beneath base path '/actuator'
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: dev
eureka:
  instance:
    #    prefer-ip-address: true
    hostname: localhost
  #    securePortEnabled: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      default-zone: http://localhost:8761/eureka/

  server:
    waitTimeInMsWhenSyncEmpty: 0
    peer-node-read-timeout-ms: 2000
