spring:
  application:
    name: spring-jpa
  profiles:
    active: dev


server:
  port: 8080


# Exposing 17 endpoint(s) beneath base path '/actuator'
management:
  endpoints:
    web:
      exposure:
        include: "*"
#
##hystrix的超时时间
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: true
#        isolation:
#          thread:
#            timeoutInMilliseconds: 30000
##ribbon的超时时间
#ribbon:
#  ReadTimeout: 30000
#  ConnectTimeout: 30000
---
spring:
  profiles: dev
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      dialect:  org.hibernate.dialect.H2Dialect
      ddl-auto: update
      naming:
        physical-strateg: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/